package top.cywin.onetv.movie.catvod.utils;

import java.util.HashMap;
import java.util.Map;

public class ZhuToPin {

    private static final Map<String, String> map = new HashMap<>();

    static {
        map.put("ㄅㄧ�?, "bie");
        map.put("ㄅㄧ�?, "biao");
        map.put("ㄅㄧ�?, "bian");
        map.put("ㄅㄧ�?, "bin");
        map.put("ㄅㄧ�?, "bing");
        map.put("ㄅㄨ", "bu");
        map.put("ㄅㄚ", "ba");
        map.put("ㄅㄛ", "bo");
        map.put("ㄅㄞ", "bai");
        map.put("ㄅㄟ", "bei");
        map.put("ㄅㄠ", "bao");
        map.put("ㄅㄢ", "ban");
        map.put("ㄅㄣ", "ben");
        map.put("ㄅㄤ", "bang");
        map.put("ㄅㄥ", "beng");
        map.put("ㄅㄧ", "bi");
        map.put("ㄆㄧ�?, "pie");
        map.put("ㄆㄧ�?, "piao");
        map.put("ㄆㄧ�?, "pian");
        map.put("ㄆㄧ�?, "pin");
        map.put("ㄆㄧ�?, "ping");
        map.put("ㄆㄨ", "pu");
        map.put("ㄆㄚ", "pa");
        map.put("ㄆㄛ", "po");
        map.put("ㄆㄞ", "pai");
        map.put("ㄆㄟ", "pei");
        map.put("ㄆㄠ", "pao");
        map.put("ㄆㄡ", "pou");
        map.put("ㄆㄢ", "pan");
        map.put("ㄆㄣ", "pen");
        map.put("ㄆㄤ", "pang");
        map.put("ㄆㄥ", "peng");
        map.put("ㄆㄧ", "pi");
        map.put("ㄇㄧ�?, "mie");
        map.put("ㄇㄧ�?, "miao");
        map.put("ㄇㄧ�?, "miu");
        map.put("ㄇㄧ�?, "mian");
        map.put("ㄇㄧ�?, "min");
        map.put("ㄇㄨ", "mu");
        map.put("ㄇㄚ", "ma");
        map.put("ㄇㄛ", "mo");
        map.put("ㄇㄜ", "me");
        map.put("ㄇㄞ", "mai");
        map.put("ㄇㄟ", "mei");
        map.put("ㄇㄠ", "mao");
        map.put("ㄇㄡ", "mou");
        map.put("ㄇㄢ", "man");
        map.put("ㄇㄣ", "men");
        map.put("ㄇㄤ", "mang");
        map.put("ㄇㄥ", "meng");
        map.put("ㄇㄧ", "mi");
        map.put("ㄈㄚ", "fa");
        map.put("ㄈㄛ", "fo");
        map.put("ㄈㄜ", "fe");
        map.put("ㄈㄟ", "fei");
        map.put("ㄈㄡ", "fou");
        map.put("ㄈㄢ", "fan");
        map.put("ㄈㄣ", "fen");
        map.put("ㄈㄤ", "fang");
        map.put("ㄈㄥ", "feng");
        map.put("ㄈㄨ", "fu");
        map.put("ㄉㄧ�?, "die");
        map.put("ㄉㄧ�?, "diao");
        map.put("ㄉㄧ�?, "diu");
        map.put("ㄉㄧ�?, "dian");
        map.put("ㄉㄧ�?, "ding");
        map.put("ㄉㄨ�?, "duo");
        map.put("ㄉㄨ�?, "dui");
        map.put("ㄉㄨ�?, "duan");
        map.put("ㄉㄨ�?, "dun");
        map.put("ㄉㄚ", "da");
        map.put("ㄉㄜ", "de");
        map.put("ㄉㄞ", "dai");
        map.put("ㄉㄟ", "dei");
        map.put("ㄉㄠ", "dao");
        map.put("ㄉㄡ", "dou");
        map.put("ㄉㄢ", "dan");
        map.put("ㄉㄣ", "den");
        map.put("ㄉㄤ", "dang");
        map.put("ㄉㄥ", "deng");
        map.put("ㄉㄧ", "di");
        map.put("ㄉㄨ", "du");
        map.put("ㄊㄧ�?, "tie");
        map.put("ㄊㄧ�?, "tiao");
        map.put("ㄊㄧ�?, "tian");
        map.put("ㄊㄧ�?, "ting");
        map.put("ㄊㄨ�?, "tuo");
        map.put("ㄊㄨ�?, "tui");
        map.put("ㄊㄨ�?, "tuan");
        map.put("ㄊㄨ�?, "tun");
        map.put("ㄊㄚ", "ta");
        map.put("ㄊㄜ", "te");
        map.put("ㄊㄞ", "tai");
        map.put("ㄊㄠ", "tao");
        map.put("ㄊㄡ", "tou");
        map.put("ㄊㄢ", "tan");
        map.put("ㄊㄤ", "tang");
        map.put("ㄊㄥ", "teng");
        map.put("ㄊㄧ", "ti");
        map.put("ㄊㄨ", "tu");
        map.put("ㄋㄧ�?, "nie");
        map.put("ㄋㄧ�?, "niao");
        map.put("ㄋㄧ�?, "niu");
        map.put("ㄋㄧ�?, "nian");
        map.put("ㄋㄧ�?, "nin");
        map.put("ㄋㄧ�?, "niang");
        map.put("ㄋㄧ�?, "ning");
        map.put("ㄋㄨ�?, "nuo");
        map.put("ㄋㄨ�?, "nuan");
        map.put("ㄋㄨ�?, "nun");
        map.put("ㄋㄨ�?, "nung");
        map.put("ㄋㄚ", "na");
        map.put("ㄋㄜ", "ne");
        map.put("ㄋㄞ", "nai");
        map.put("ㄋㄟ", "nei");
        map.put("ㄋㄠ", "nao");
        map.put("ㄋㄡ", "nou");
        map.put("ㄋㄢ", "nan");
        map.put("ㄋㄣ", "nen");
        map.put("ㄋㄤ", "nang");
        map.put("ㄋㄥ", "neng");
        map.put("ㄋㄧ", "ni");
        map.put("ㄋㄨ", "nu");
        map.put("ㄌㄧ�?, "lia");
        map.put("ㄌㄧ�?, "lie");
        map.put("ㄌㄧ�?, "liao");
        map.put("ㄌㄧ�?, "liu");
        map.put("ㄌㄧ�?, "lian");
        map.put("ㄌㄧ�?, "lin");
        map.put("ㄌㄧ�?, "liang");
        map.put("ㄌㄧ�?, "ling");
        map.put("ㄌㄨ�?, "luo");
        map.put("ㄌㄨ�?, "luan");
        map.put("ㄌㄨ�?, "lun");
        map.put("ㄌㄨ�?, "lung");
        map.put("ㄌㄩ", "lv");
        map.put("ㄌㄩ�?, "lve");
        map.put("ㄌㄚ", "la");
        map.put("ㄌㄛ", "lo");
        map.put("ㄌㄜ", "le");
        map.put("ㄌㄞ", "lai");
        map.put("ㄌㄟ", "lei");
        map.put("ㄌㄠ", "lao");
        map.put("ㄌㄡ", "lou");
        map.put("ㄌㄢ", "lan");
        map.put("ㄌㄣ", "len");
        map.put("ㄌㄤ", "lang");
        map.put("ㄌㄥ", "leng");
        map.put("ㄌㄧ", "li");
        map.put("ㄌㄨ", "lu");
        map.put("ㄍㄨ�?, "gua");
        map.put("ㄍㄨ�?, "guo");
        map.put("ㄍㄨ�?, "guai");
        map.put("ㄍㄨ�?, "gui");
        map.put("ㄍㄨ�?, "guan");
        map.put("ㄍㄨ�?, "gun");
        map.put("ㄍㄨ�?, "guang");
        map.put("ㄍㄨ�?, "gong");
        map.put("ㄍㄚ", "ga");
        map.put("ㄍㄜ", "ge");
        map.put("ㄍㄞ", "gai");
        map.put("ㄍㄟ", "gei");
        map.put("ㄍㄠ", "gao");
        map.put("ㄍㄡ", "gou");
        map.put("ㄍㄢ", "gan");
        map.put("ㄍㄣ", "gen");
        map.put("ㄍㄤ", "gang");
        map.put("ㄍㄥ", "geng");
        map.put("ㄍㄨ", "gu");
        map.put("ㄎㄨ�?, "kua");
        map.put("ㄎㄨ�?, "kuo");
        map.put("ㄎㄨ�?, "kuai");
        map.put("ㄎㄨ�?, "kui");
        map.put("ㄎㄨ�?, "kuan");
        map.put("ㄎㄨ�?, "kun");
        map.put("ㄎㄨ�?, "kuang");
        map.put("ㄎㄨ�?, "kong");
        map.put("ㄎㄚ", "ka");
        map.put("ㄎㄜ", "ke");
        map.put("ㄎㄞ", "kai");
        map.put("ㄎㄠ", "kao");
        map.put("ㄎㄡ", "kou");
        map.put("ㄎㄢ", "kan");
        map.put("ㄎㄣ", "ken");
        map.put("ㄎㄤ", "kang");
        map.put("ㄎㄥ", "keng");
        map.put("ㄎㄨ", "ku");
        map.put("ㄏㄨ�?, "hua");
        map.put("ㄏㄨ�?, "huo");
        map.put("ㄏㄨ�?, "huai");
        map.put("ㄏㄨ�?, "huai");
        map.put("ㄏㄨ�?, "huan");
        map.put("ㄏㄨ�?, "hun");
        map.put("ㄏㄨ�?, "huang");
        map.put("ㄏㄨ�?, "hong");
        map.put("ㄏㄚ", "ha");
        map.put("ㄏㄜ", "he");
        map.put("ㄏㄞ", "hai");
        map.put("ㄏㄟ", "hei");
        map.put("ㄏㄠ", "hao");
        map.put("ㄏㄡ", "hou");
        map.put("ㄏㄢ", "han");
        map.put("ㄏㄣ", "hen");
        map.put("ㄏㄤ", "hang");
        map.put("ㄏㄥ", "heng");
        map.put("ㄏㄨ", "hu");
        map.put("ㄐㄧ�?, "jia");
        map.put("ㄐㄧ�?, "jie");
        map.put("ㄐㄧ�?, "jiao");
        map.put("ㄐㄧ�?, "jiu");
        map.put("ㄐㄧ�?, "jian");
        map.put("ㄐㄧ�?, "jin");
        map.put("ㄐㄧ�?, "jiang");
        map.put("ㄐㄧ�?, "jing");
        map.put("ㄐㄩ�?, "jue");
        map.put("ㄐㄩ�?, "juan");
        map.put("ㄐㄩ�?, "jun");
        map.put("ㄐㄩ�?, "jiong");
        map.put("ㄐㄧ", "ji");
        map.put("ㄐㄩ", "ju");
        map.put("ㄑㄧ�?, "qia");
        map.put("ㄑㄧ�?, "qie");
        map.put("ㄑㄧ�?, "qiao");
        map.put("ㄑㄧ�?, "qiu");
        map.put("ㄑㄧ�?, "qian");
        map.put("ㄑㄧ�?, "qin");
        map.put("ㄑㄧ�?, "qiang");
        map.put("ㄑㄧ�?, "qing");
        map.put("ㄑㄩ�?, "que");
        map.put("ㄑㄩ�?, "quan");
        map.put("ㄑㄩ�?, "qun");
        map.put("ㄑㄩ�?, "qun");
        map.put("ㄑㄧ", "qi");
        map.put("ㄑㄩ", "qu");
        map.put("ㄒㄧ�?, "xia");
        map.put("ㄒㄧ�?, "xie");
        map.put("ㄒㄧ�?, "xiao");
        map.put("ㄒㄧ�?, "xiu");
        map.put("ㄒㄧ�?, "xian");
        map.put("ㄒㄧ�?, "xin");
        map.put("ㄒㄧ�?, "xiang");
        map.put("ㄒㄧ�?, "xing");
        map.put("ㄒㄩ�?, "xue");
        map.put("ㄒㄩ�?, "xuan");
        map.put("ㄒㄩ�?, "xun");
        map.put("ㄒㄩ�?, "xiong");
        map.put("ㄒㄧ", "xi");
        map.put("ㄒㄩ", "xu");
        map.put("ㄓㄨ�?, "zhua");
        map.put("ㄓㄨ�?, "zhuo");
        map.put("ㄓㄨ�?, "zhuai");
        map.put("ㄓㄨ�?, "zhuo");
        map.put("ㄓㄨ�?, "zhuan");
        map.put("ㄓㄨ�?, "zhuan");
        map.put("ㄓㄨ�?, "zhuan");
        map.put("ㄓㄨ�?, "zhong");
        map.put("ㄓㄚ", "zha");
        map.put("ㄓㄜ", "zhe");
        map.put("ㄓㄞ", "zhai");
        map.put("ㄓㄟ", "zhei");
        map.put("ㄓㄠ", "zhao");
        map.put("ㄓㄡ", "zhou");
        map.put("ㄓㄢ", "zhan");
        map.put("ㄓㄣ", "zhen");
        map.put("ㄓㄤ", "zhang");
        map.put("ㄓㄥ", "zheng");
        map.put("ㄓㄨ", "zhu");
        map.put("ㄔㄨ�?, "chua");
        map.put("ㄔㄨ�?, "chuo");
        map.put("ㄔㄨ�?, "chuai");
        map.put("ㄔㄨ�?, "chui");
        map.put("ㄔㄨ�?, "chuan");
        map.put("ㄔㄨ�?, "chun");
        map.put("ㄔㄨ�?, "chuang");
        map.put("ㄔㄨ�?, "chong");
        map.put("ㄔㄚ", "cha");
        map.put("ㄔㄜ", "che");
        map.put("ㄔㄞ", "chai");
        map.put("ㄔㄠ", "chao");
        map.put("ㄔㄡ", "chou");
        map.put("ㄔㄢ", "chan");
        map.put("ㄔㄣ", "chen");
        map.put("ㄔㄤ", "chang");
        map.put("ㄔㄥ", "cheng");
        map.put("ㄔㄨ", "chu");
        map.put("ㄕㄨ�?, "shua");
        map.put("ㄕㄨ�?, "shuo");
        map.put("ㄕㄨ�?, "shuai");
        map.put("ㄕㄨ�?, "shui");
        map.put("ㄕㄨ�?, "shuan");
        map.put("ㄕㄨ�?, "shun");
        map.put("ㄕㄨ�?, "shuang");
        map.put("ㄕㄚ", "sha");
        map.put("ㄕㄜ", "she");
        map.put("ㄕㄞ", "shai");
        map.put("ㄕㄟ", "shei");
        map.put("ㄕㄠ", "shao");
        map.put("ㄕㄡ", "shou");
        map.put("ㄕㄢ", "shan");
        map.put("ㄕㄣ", "shen");
        map.put("ㄕㄤ", "shang");
        map.put("ㄕㄥ", "sheng");
        map.put("ㄕㄨ", "shu");
        map.put("ㄖㄨ�?, "ruo");
        map.put("ㄖㄨ�?, "rui");
        map.put("ㄖㄨ�?, "ruan");
        map.put("ㄖㄨ�?, "run");
        map.put("ㄖㄨ�?, "rung");
        map.put("ㄖㄜ", "re");
        map.put("ㄖㄠ", "rao");
        map.put("ㄖㄡ", "rou");
        map.put("ㄖㄢ", "ran");
        map.put("ㄖㄣ", "ren");
        map.put("ㄖㄤ", "rang");
        map.put("ㄖㄥ", "reng");
        map.put("ㄖㄨ", "ru");
        map.put("ㄗㄨ�?, "zuo");
        map.put("ㄗㄨ�?, "zui");
        map.put("ㄗㄨ�?, "zuan");
        map.put("ㄗㄨ�?, "zun");
        map.put("ㄗㄨ�?, "zong");
        map.put("ㄗㄚ", "za");
        map.put("ㄗㄜ", "ze");
        map.put("ㄗㄞ", "zai");
        map.put("ㄗㄟ", "zei");
        map.put("ㄗㄠ", "zao");
        map.put("ㄗㄡ", "zou");
        map.put("ㄗㄢ", "zan");
        map.put("ㄗㄣ", "zen");
        map.put("ㄗㄤ", "zang");
        map.put("ㄗㄥ", "zeng");
        map.put("ㄗㄨ", "zu");
        map.put("ㄘㄨ�?, "cuo");
        map.put("ㄘㄨ�?, "cui");
        map.put("ㄘㄨ�?, "cuan");
        map.put("ㄘㄨ�?, "cun");
        map.put("ㄘㄨ�?, "cong");
        map.put("ㄘㄚ", "ca");
        map.put("ㄘㄜ", "ce");
        map.put("ㄘㄞ", "cai");
        map.put("ㄘㄠ", "cao");
        map.put("ㄘㄡ", "cou");
        map.put("ㄘㄢ", "can");
        map.put("ㄘㄣ", "cen");
        map.put("ㄘㄤ", "cang");
        map.put("ㄘㄥ", "ceng");
        map.put("ㄘㄨ", "cu");
        map.put("ㄙㄨ�?, "suo");
        map.put("ㄙㄨ�?, "sui");
        map.put("ㄙㄨ�?, "suan");
        map.put("ㄙㄨ�?, "sun");
        map.put("ㄙㄨ�?, "song");
        map.put("ㄙㄚ", "sa");
        map.put("ㄙㄜ", "se");
        map.put("ㄙㄞ", "sai");
        map.put("ㄙㄟ", "sei");
        map.put("ㄙㄠ", "sao");
        map.put("ㄙㄡ", "sou");
        map.put("ㄙㄢ", "san");
        map.put("ㄙㄣ", "sen");
        map.put("ㄙㄤ", "sang");
        map.put("ㄙㄥ", "seng");
        map.put("ㄙㄨ", "su");
        map.put("ㄧㄚ", "ya");
        map.put("ㄧㄛ", "yo");
        map.put("ㄧㄝ", "ye");
        map.put("ㄧㄞ", "yai");
        map.put("ㄧㄠ", "yao");
        map.put("ㄧㄡ", "you");
        map.put("ㄧㄢ", "yan");
        map.put("ㄧㄣ", "yin");
        map.put("ㄧㄤ", "yang");
        map.put("ㄧㄥ", "ying");
        map.put("ㄨㄚ", "wa");
        map.put("ㄨㄛ", "wo");
        map.put("ㄨㄞ", "wai");
        map.put("ㄨㄟ", "wei");
        map.put("ㄨㄢ", "wan");
        map.put("ㄨㄣ", "wen");
        map.put("ㄨㄤ", "wang");
        map.put("ㄨㄥ", "weng");
        map.put("ㄩㄝ", "yue");
        map.put("ㄩㄢ", "yuan");
        map.put("ㄩㄣ", "yun");
        map.put("ㄩㄥ", "yong");
        map.put("�?, "b");
        map.put("�?, "p");
        map.put("�?, "m");
        map.put("�?, "f");
        map.put("�?, "d");
        map.put("�?, "t");
        map.put("�?, "n");
        map.put("�?, "l");
        map.put("�?, "g");
        map.put("�?, "k");
        map.put("�?, "h");
        map.put("�?, "j");
        map.put("�?, "q");
        map.put("�?, "x");
        map.put("�?, "zh");
        map.put("�?, "ch");
        map.put("�?, "sh");
        map.put("�?, "r");
        map.put("�?, "z");
        map.put("�?, "c");
        map.put("�?, "s");
        map.put("�?, "yi");
        map.put("�?, "wu");
        map.put("�?, "yu");
        map.put("�?, "a");
        map.put("�?, "o");
        map.put("�?, "e");
        map.put("�?, "eh");
        map.put("�?, "ai");
        map.put("�?, "ei");
        map.put("�?, "ao");
        map.put("�?, "ou");
        map.put("�?, "an");
        map.put("�?, "en");
        map.put("�?, "ang");
        map.put("�?, "eng");
        map.put("�?, "er");
    }

    public static String get(String text) {
        StringBuilder sb = new StringBuilder();
        String[] splits = text.split("�?);
        if (splits.length > 1) findSplit(sb, splits);
        else findSingle(sb, text);
        return sb.toString();
    }

    private static void findSplit(StringBuilder sb, String[] splits) {
        for (String split : splits) {
            String pinyin = map.get(split);
            sb.append(pinyin != null ? pinyin : split);
        }
    }

    private static void findSingle(StringBuilder sb, String text) {
        for (char chars : text.toCharArray()) {
            String pinyin = map.get(String.valueOf(chars));
            sb.append(pinyin != null ? pinyin : chars);
        }
    }
}
