package com.fongmi.android.tv.event;

import org.greenrobot.eventbus.meta.SimpleSubscriberInfo;
import org.greenrobot.eventbus.meta.SubscriberMethodInfo;
import org.greenrobot.eventbus.meta.SubscriberInfo;
import org.greenrobot.eventbus.meta.SubscriberInfoIndex;

import org.greenrobot.eventbus.ThreadMode;

import java.util.HashMap;
import java.util.Map;

/** This class is generated by EventBus, do not edit. */
public class EventIndex implements SubscriberInfoIndex {
    private static final Map<Class<?>, SubscriberInfo> SUBSCRIBER_INDEX;

    static {
        SUBSCRIBER_INDEX = new HashMap<Class<?>, SubscriberInfo>();

        putIndex(new SimpleSubscriberInfo(com.fongmi.android.tv.ui.activity.VideoActivity.class, true,
                new SubscriberMethodInfo[] {
            new SubscriberMethodInfo("onActionEvent", ActionEvent.class, ThreadMode.MAIN),
            new SubscriberMethodInfo("onRefreshEvent", RefreshEvent.class, ThreadMode.MAIN),
            new SubscriberMethodInfo("onPlayerEvent", PlayerEvent.class, ThreadMode.MAIN),
            new SubscriberMethodInfo("onErrorEvent", ErrorEvent.class, ThreadMode.MAIN),
        }));

        putIndex(new SimpleSubscriberInfo(com.fongmi.android.tv.ui.activity.HomeActivity.class, true,
                new SubscriberMethodInfo[] {
            new SubscriberMethodInfo("onRefreshEvent", RefreshEvent.class, ThreadMode.MAIN),
            new SubscriberMethodInfo("onServerEvent", ServerEvent.class, ThreadMode.MAIN),
            new SubscriberMethodInfo("onCastEvent", CastEvent.class, ThreadMode.MAIN),
        }));

        putIndex(new SimpleSubscriberInfo(com.fongmi.android.tv.ui.activity.KeepActivity.class, true,
                new SubscriberMethodInfo[] {
            new SubscriberMethodInfo("onRefreshEvent", RefreshEvent.class, ThreadMode.MAIN),
        }));

        putIndex(new SimpleSubscriberInfo(com.fongmi.android.tv.ui.dialog.UaDialog.class, true,
                new SubscriberMethodInfo[] {
            new SubscriberMethodInfo("onServerEvent", ServerEvent.class, ThreadMode.MAIN),
        }));

        putIndex(new SimpleSubscriberInfo(com.fongmi.android.tv.service.PlaybackService.class, true,
                new SubscriberMethodInfo[] {
            new SubscriberMethodInfo("onActionEvent", ActionEvent.class, ThreadMode.MAIN),
        }));

        putIndex(new SimpleSubscriberInfo(com.fongmi.android.tv.ui.dialog.ConfigDialog.class, true,
                new SubscriberMethodInfo[] {
            new SubscriberMethodInfo("onServerEvent", ServerEvent.class, ThreadMode.MAIN),
        }));

        putIndex(new SimpleSubscriberInfo(com.fongmi.android.tv.ui.activity.LiveActivity.class, true,
                new SubscriberMethodInfo[] {
            new SubscriberMethodInfo("onActionEvent", ActionEvent.class, ThreadMode.MAIN),
            new SubscriberMethodInfo("onRefreshEvent", RefreshEvent.class, ThreadMode.MAIN),
            new SubscriberMethodInfo("onPlayerEvent", PlayerEvent.class, ThreadMode.MAIN),
            new SubscriberMethodInfo("onErrorEvent", ErrorEvent.class, ThreadMode.MAIN),
        }));

        // CastActivity 不存在于 mobile flavor，故不注册

        putIndex(new SimpleSubscriberInfo(com.fongmi.android.tv.ui.dialog.ProxyDialog.class, true,
                new SubscriberMethodInfo[] {
            new SubscriberMethodInfo("onServerEvent", ServerEvent.class, ThreadMode.MAIN),
        }));

        putIndex(new SimpleSubscriberInfo(com.fongmi.android.tv.ui.base.BaseActivity.class, true,
                new SubscriberMethodInfo[] {
            new SubscriberMethodInfo("onRefreshEvent", RefreshEvent.class, ThreadMode.MAIN),
        }));

    }

    private static void putIndex(SubscriberInfo info) {
        SUBSCRIBER_INDEX.put(info.getSubscriberClass(), info);
    }

    @Override
    public SubscriberInfo getSubscriberInfo(Class<?> subscriberClass) {
        SubscriberInfo info = SUBSCRIBER_INDEX.get(subscriberClass);
        if (info != null) {
            return info;
        } else {
            return null;
        }
    }
} 