package top.cywin.onetv.vod.event;

import top.cywin.onetv.vod.service.PlaybackService;
import top.cywin.onetv.vod.ui.activity.CastActivity;
import top.cywin.onetv.vod.ui.activity.HomeActivity;
import top.cywin.onetv.vod.ui.activity.KeepActivity;
import top.cywin.onetv.vod.ui.activity.LiveActivity;
import top.cywin.onetv.vod.ui.activity.VideoActivity;
import top.cywin.onetv.vod.ui.base.BaseActivity;
import top.cywin.onetv.vod.ui.dialog.ConfigDialog;
import top.cywin.onetv.vod.ui.dialog.ProxyDialog;
import top.cywin.onetv.vod.ui.dialog.UaDialog;

import org.greenrobot.eventbus.meta.SimpleSubscriberInfo;
import org.greenrobot.eventbus.meta.SubscriberMethodInfo;
import org.greenrobot.eventbus.meta.SubscriberInfo;
import org.greenrobot.eventbus.meta.SubscriberInfoIndex;

import org.greenrobot.eventbus.ThreadMode;

import java.util.HashMap;
import java.util.Map;

/** This class is generated by EventBus, do not edit. */
public class EventIndex implements SubscriberInfoIndex {
    private static final Map<Class<?>, SubscriberInfo> SUBSCRIBER_INDEX;

    static {
        SUBSCRIBER_INDEX = new HashMap<Class<?>, SubscriberInfo>();

        putIndex(new SimpleSubscriberInfo(VideoActivity.class, true,
                new SubscriberMethodInfo[] {
            new SubscriberMethodInfo("onActionEvent", ActionEvent.class, ThreadMode.MAIN),
            new SubscriberMethodInfo("onRefreshEvent", RefreshEvent.class, ThreadMode.MAIN),
            new SubscriberMethodInfo("onPlayerEvent", PlayerEvent.class, ThreadMode.MAIN),
            new SubscriberMethodInfo("onErrorEvent", ErrorEvent.class, ThreadMode.MAIN),
        }));

        putIndex(new SimpleSubscriberInfo(HomeActivity.class, true,
                new SubscriberMethodInfo[] {
            new SubscriberMethodInfo("onRefreshEvent", RefreshEvent.class, ThreadMode.MAIN),
            new SubscriberMethodInfo("onServerEvent", ServerEvent.class, ThreadMode.MAIN),
            new SubscriberMethodInfo("onCastEvent", CastEvent.class, ThreadMode.MAIN),
        }));

        putIndex(new SimpleSubscriberInfo(KeepActivity.class, true,
                new SubscriberMethodInfo[] {
            new SubscriberMethodInfo("onRefreshEvent", RefreshEvent.class, ThreadMode.MAIN),
        }));

        putIndex(new SimpleSubscriberInfo(UaDialog.class, true,
                new SubscriberMethodInfo[] {
            new SubscriberMethodInfo("onServerEvent", ServerEvent.class, ThreadMode.MAIN),
        }));

        putIndex(new SimpleSubscriberInfo(PlaybackService.class, true,
                new SubscriberMethodInfo[] {
            new SubscriberMethodInfo("onActionEvent", ActionEvent.class, ThreadMode.MAIN),
        }));

        putIndex(new SimpleSubscriberInfo(ConfigDialog.class, true,
                new SubscriberMethodInfo[] {
            new SubscriberMethodInfo("onServerEvent", ServerEvent.class, ThreadMode.MAIN),
        }));

        putIndex(new SimpleSubscriberInfo(LiveActivity.class, true,
                new SubscriberMethodInfo[] {
            new SubscriberMethodInfo("onActionEvent", ActionEvent.class, ThreadMode.MAIN),
            new SubscriberMethodInfo("onRefreshEvent", RefreshEvent.class, ThreadMode.MAIN),
            new SubscriberMethodInfo("onPlayerEvent", PlayerEvent.class, ThreadMode.MAIN),
            new SubscriberMethodInfo("onErrorEvent", ErrorEvent.class, ThreadMode.MAIN),
        }));

        putIndex(new SimpleSubscriberInfo(CastActivity.class, true,
                new SubscriberMethodInfo[] {
            new SubscriberMethodInfo("onActionEvent", ActionEvent.class, ThreadMode.MAIN),
            new SubscriberMethodInfo("onRefreshEvent", RefreshEvent.class, ThreadMode.MAIN),
            new SubscriberMethodInfo("onPlayerEvent", PlayerEvent.class, ThreadMode.MAIN),
            new SubscriberMethodInfo("onErrorEvent", ErrorEvent.class, ThreadMode.MAIN),
        }));

        putIndex(new SimpleSubscriberInfo(ProxyDialog.class, true,
                new SubscriberMethodInfo[] {
            new SubscriberMethodInfo("onServerEvent", ServerEvent.class, ThreadMode.MAIN),
        }));

        putIndex(new SimpleSubscriberInfo(BaseActivity.class, true,
                new SubscriberMethodInfo[] {
            new SubscriberMethodInfo("onRefreshEvent", RefreshEvent.class, ThreadMode.MAIN),
        }));

    }

    private static void putIndex(SubscriberInfo info) {
        SUBSCRIBER_INDEX.put(info.getSubscriberClass(), info);
    }

    @Override
    public SubscriberInfo getSubscriberInfo(Class<?> subscriberClass) {
        SubscriberInfo info = SUBSCRIBER_INDEX.get(subscriberClass);
        if (info != null) {
            return info;
        } else {
            return null;
        }
    }
} 